version: '3.8'
services:
  app: 
    # Especificamos al yml que el Dockerfile se encuentra en al misma direccion
    build: .
    # Indicamos que lo que cambiemos aca se replique en /django
    # - origen:destino
    volumes:
      - .:/django
    # Expone el port 8000 en el container
    ports:
      - 8000:8000
    # Le damos un nombre al servicio, con un tag
    image: app:django
    container_name: django_container
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - db
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    container_name: postgres_db