# Generated by Django 3.2.9 on 2022-01-20 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
