# Generated by Django 3.2.9 on 2022-01-19 19:31

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Airport',
                'verbose_name_plural': 'Airports',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Country',
                'verbose_name_plural': 'Countries',
            },
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(0, 'Available'), (1, 'Not Available'), (2, 'Blocked')], default=0)),
                ('code_number', models.IntegerField()),
                ('flight_type', models.CharField(choices=[('Normal', 'Normal'), ('Sale', 'Sale')], default='Normal', max_length=10)),
                ('hours', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99)])),
                ('date', models.DateField()),
                ('turn', models.BooleanField(default=False)),
                ('price', models.FloatField(default=0.0)),
                ('airport_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Desde', to='despegar.airport')),
                ('airport_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Hasta', to='despegar.airport')),
            ],
            options={
                'verbose_name': 'Flight',
                'verbose_name_plural': 'Flights',
            },
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(0, 'Available'), (1, 'Not Available'), (2, 'Blocked')], default=0)),
                ('name', models.CharField(max_length=50)),
                ('hotel_type', models.CharField(choices=[('Normal', 'Normal'), ('Sale', 'Sale')], default='Normal', max_length=10)),
                ('stars', models.IntegerField(choices=[(0, 'No stars'), (1, '1 star'), (2, '2 stars'), (3, '3 stars'), (4, '4 stars'), (5, '5 stars')], default=0)),
                ('address', models.CharField(max_length=50)),
                ('priceperday', models.FloatField(default=0.0, verbose_name='Price per day')),
            ],
            options={
                'verbose_name': 'Hotel',
                'verbose_name_plural': 'Hotels',
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(0, 'Available'), (1, 'Not Available'), (2, 'Blocked')], default=0)),
                ('patent', models.IntegerField()),
                ('brand', models.CharField(max_length=20)),
                ('priceperday', models.FloatField(default=0.0, verbose_name='Price per day')),
            ],
            options={
                'verbose_name': 'Vehicle',
                'verbose_name_plural': 'Vehicles',
            },
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Country', to='despegar.country')),
            ],
            options={
                'verbose_name': 'Province',
                'verbose_name_plural': 'Provinces',
            },
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(0, 'Available'), (1, 'Not Available'), (2, 'Blocked')], default=0)),
                ('price', models.FloatField(default=0.0)),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='despegar.flight')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='despegar.hotel')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='despegar.vehicle')),
            ],
            options={
                'verbose_name': 'Package',
                'verbose_name_plural': 'Packages',
            },
        ),
        migrations.AddField(
            model_name='airport',
            name='province',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Province', to='despegar.province'),
        ),
    ]
