# Generated by Django 3.2.9 on 2021-11-09 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('despegar', '0003_auto_20211108_2351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airport',
            name='province',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Provincia', to='despegar.province'),
        ),
    ]
