# Generated by Django 3.2.9 on 2022-01-19 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('despegar', '0005_auto_20220119_0219'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='price',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='priceperday',
            field=models.FloatField(default=0.0, verbose_name='Price per day'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='flight_type',
            field=models.CharField(choices=[('Normal', 'Normal'), ('Sale', 'Sale')], default='Normal', max_length=10),
        ),
    ]
