# Generated by Django 3.2.9 on 2022-01-19 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('despegar', '0006_auto_20220119_0228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='flight_type',
            field=models.CharField(choices=[('Sale', 'Sale'), ('Normal', 'Normal')], default='Normal', max_length=10),
        ),
    ]
