# Generated by Django 3.2.9 on 2022-01-19 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('despegar', '0008_auto_20220119_0235'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='price',
        ),
        migrations.AddField(
            model_name='hotel',
            name='priceperday',
            field=models.FloatField(default=0.0, verbose_name='Price per day'),
        ),
    ]
