# Generated by Django 3.2.9 on 2022-01-31 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('despegar', '0008_auto_20220125_2105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='flight',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flight', to='despegar.flight'),
        ),
        migrations.AlterField(
            model_name='package',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotel', to='despegar.hotel'),
        ),
        migrations.AlterField(
            model_name='package',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle', to='despegar.vehicle'),
        ),
    ]
