# Generated by Django 3.2.9 on 2022-01-19 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('despegar', '0010_auto_20220119_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='price',
            field=models.FloatField(default=0.0),
        ),
    ]
