# Generated by Django 3.2.9 on 2022-02-01 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('despegar', '0011_auto_20220131_2043'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='status',
            field=models.IntegerField(choices=[(0, 'In process'), (1, 'Purchased'), (2, 'Canceled')], default=0),
        ),
    ]
