# Generated by Django 3.2.9 on 2022-02-01 18:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('despegar', '0016_auto_20220201_1813'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='amount',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99)]),
        ),
        migrations.AlterField(
            model_name='flight',
            name='flight_type',
            field=models.CharField(choices=[('Sale', 'Sale'), ('Normal', 'Normal')], default='Normal', max_length=10),
        ),
        migrations.AlterField(
            model_name='flight',
            name='status',
            field=models.IntegerField(choices=[(0, 'Available'), (1, 'Not Available'), (2, 'Blocked')], default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2)]),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='hotel_type',
            field=models.CharField(choices=[('Sale', 'Sale'), ('Normal', 'Normal')], default='Normal', max_length=10),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='stars',
            field=models.IntegerField(choices=[(0, 'No stars'), (1, '1 star'), (2, '2 stars'), (3, '3 stars'), (4, '4 stars'), (5, '5 stars')], default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='status',
            field=models.IntegerField(choices=[(0, 'Available'), (1, 'Not Available'), (2, 'Blocked')], default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2)]),
        ),
        migrations.AlterField(
            model_name='package',
            name='status',
            field=models.IntegerField(choices=[(0, 'Available'), (1, 'Not Available'), (2, 'Blocked')], default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2)]),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='status',
            field=models.IntegerField(choices=[(0, 'In process'), (1, 'Purchased'), (2, 'Canceled')], default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2)]),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='status',
            field=models.IntegerField(choices=[(0, 'Available'), (1, 'Not Available'), (2, 'Blocked')], default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2)]),
        ),
    ]
